### ISSUE TITLE
Fix all remaining errors with the Amber unit tests

### ISSUE THREAD

**Issue by multiplemonomials** [Amber-MD/cmake-buildscripts#18]
```
txmin.nab: line 4: file 'xmin_opt.h' not found
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 1 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 2 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 3 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 4 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 5 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 6 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 7 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 8 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 9 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 10 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 11 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 12 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 13 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 14 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 15 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 16 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 17 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 18 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 19 has invalid symbol index 21
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_line): relocation 0 has invalid symbol index 2
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
./Run.xmin: 14: ./Run.xmin: ./txmin: not found
./Run.xmin: Program error
make[1]: *** [xmin_test] Error 1
Running test on netcdf files

tnetcdf.nab: line 3: file 'nab_netcdf.h' not found
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 1 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 2 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 3 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 4 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 5 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 6 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 7 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 8 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 9 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 10 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 11 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 12 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 13 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 14 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 15 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 16 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 17 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 18 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 19 has invalid symbol index 21
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_line): relocation 0 has invalid symbol index 2
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
./Run.netcdf: 14: ./Run.netcdf: ./tnetcdf: not found
./Run.netcdf: Program error
make[1]: *** [netcdf_test] Error 1
Running test for variable 1-4 scaled nonbonded interactions

diffing variable_14scale.out.check with variable_14scale.out
PASSED
==============================================================
Running test to do simple lmod optimization

tlmod.nab: line 4: file 'xmin_opt.h' not found
tlmod.nab: line 5: file 'lmod_opt.h' not found
diffing T1.crd with T2.crd
PASSED
==============================================================
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 1 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 2 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 3 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 4 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 5 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 6 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 7 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 8 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 9 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 10 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 11 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 12 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 13 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 14 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 15 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 16 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 17 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 18 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 19 has invalid symbol index 21
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_line): relocation 0 has invalid symbol index 2
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
./Run.lmod: 14: ./Run.lmod: ./tlmod: not found
diffing tlmod.out.check with tlmod.out
```
^ My `nab++` wrapper does not handle preprocessor errors, and some headers are obviously missing

**Comment by multiplemonomials** [comment]
```
==============================================================

  CPPTRAJ: Data filter test.
Error: '../Test_Diffusion/diff_a.xmgr': No such file or directory
Error: Could not read data file '../Test_Diffusion/diff_a.xmgr'.
	1 errors encountered reading input.
Error: Error(s) occurred during execution.
Error: cpptraj exited with status 1
possible FAILURE:  file datafilter.dat does not exist.
```

**Comment by multiplemonomials** [comment]
I fixed some (mis)use of relative paths in `test.FEW`, and now the FEW tests run properly

**Comment by multiplemonomials** [comment]
NAB test errors are fixed by master commit `a91bb95346`.  Turns out that it was passing the `-I` argument to the preprocessor incorrectly, and that the preprocessor was returning exit code 256, which rolled over to 0 when stored in an `int8_t`

**Comment by multiplemonomials** [comment]
Hmm, in `test/Makefile`, `test.serial.sander.MM` lists `test.sander.LES` as a dependency, but it does not exist.  This causes an error when running tests. @agoetz Do you know what's up with this?

**Comment by multiplemonomials** [comment]
`test.serial.sanderapi` needs some serious work.  It makes heavy use of variables imported from the makefile.  We either need to make heavy changes to the makefile to make it inspect the installed system, or just replace it with a CMake script.

**Comment by multiplemonomials** [comment]
I fixed the EMIL tests in commit `fe24208181`.  It turns out that I messed up and never set the `EMIL` definition for `sander` and `pmemd`, so the tests failed once I got them running.  I added the definition to CMake and things are running properly now.

**Comment by multiplemonomials** [comment]
Commit `fe24208181` also makes `AmberTools/test/test_at_*.sh` set `TESTsander` to point to sander when running the Amber tests.  This fixes 90% of the broken `sander` tests, but breaks the 10% of them that use `sander.LES`.  I'm not really sure what to do about that.

**Comment by multiplemonomials** [comment]
Hmmm, it seems like `test_amber_clean.sh` is missing some files, specifically in the `test/4096wat`, `test/netcdf`, and `test/rism3d` directories.  Any idea what's going on?

**Comment by agoetz** [comment]
> Hmm, in test/Makefile, test.serial.sander.MM lists test.sander.LES as a dependency, but it does not exist.

I looked at the log of `$AMBERHOME/test/Makefile`. The targets `test.sander.LES` and `test.sander.LES.MPI` are still there in commit `35ca6f2e81` but not in commit `2ed4c34f68`. @multiplemonomials can you please have a look?

**Comment by multiplemonomials** [comment]
Test results with current master on OS X:
```
Finished test suite for AmberTools at Sun Aug 13 01:34:58 PDT 2017.

    1661 file comparisons passed
      33 file comparisons failed
      56 tests experienced errors
```
All of the nab tests failed because the system FFTW library was not installed to the compiler search path.

**Comment by multiplemonomials** [comment]
On OS X, MMPBSA.py is dying.
```
 /Users/jsmith/amber-install/bin/MMPBSA.py -O -i mmpbsa.in -sp complex_solvated.prmtop -cp complex.prmtop -rp receptor.prmtop -lp ligand.prmtop -y complex_solvated.mdcrd -yr receptor_solvated.mdcrd -yl ligand_solvated.mdcrd -srp receptor_solvated.prmtop -slp ligand_solvated.prmtop -o FINAL_RESULTS_MMPBSA_1.dat
Loading and checking parameter files for compatibility...
cpptraj found! Using /Users/jsmith/amber-install/bin/cpptraj
sander found! Using /Users/jsmith/amber-install/bin/sander
mmpbsa_py_nabnmode found! Using /Users/jsmith/amber-install/bin/mmpbsa_py_nabnmode
Preparing trajectories for simulation...
5 frames were processed by cpptraj for use in calculation.
5 frames were processed by cpptraj for nmode calculations.

Running calculations on normal system...

Beginning GB calculations with /Users/jsmith/amber-install/bin/sander
  calculating complex contribution...
popening ['/Users/jsmith/amber-install/bin/sander', '-O', '-i', '_MMPBSA_gb_decomp_com.mdin', '-p', 'complex.prmtop', '-c', '_MMPBSA_dummycomplex.inpcrd', '-y', '_MMPBSA_complex.mdcrd.0', '-o', '_MMPBSA_complex_gb.mdout.0', '-r', '_MMPBSA_restrt.0']
  calculating receptor contribution...
popening ['/Users/jsmith/amber-install/bin/sander', '-O', '-i', '_MMPBSA_gb_decomp_rec.mdin', '-p', 'receptor.prmtop', '-c', '_MMPBSA_dummyreceptor.inpcrd', '-y', '_MMPBSA_receptor.mdcrd.0', '-o', '_MMPBSA_receptor_gb.mdout.0', '-r', '_MMPBSA_restrt.0']
  calculating ligand contribution...
popening ['/Users/jsmith/amber-install/bin/sander', '-O', '-i', '_MMPBSA_gb_decomp_lig.mdin', '-p', 'ligand.prmtop', '-c', '_MMPBSA_dummyligand.inpcrd', '-y', '_MMPBSA_ligand.mdcrd.0', '-o', '_MMPBSA_ligand_gb.mdout.0', '-r', '_MMPBSA_restrt.0']

Beginning PB calculations with /Users/jsmith/amber-install/bin/sander
  calculating complex contribution...
  calculating receptor contribution...
  calculating ligand contribution...

Beginning nmode calculations with /Users/jsmith/amber-install/bin/mmpbsa_py_nabnmode
  calculating complex contribution...
popening ['/Users/jsmith/amber-install/bin/mmpbsa_py_nabnmode', '_MMPBSA_complex.pdb', 'complex.prmtop', '50000', '0.001', 'ntpr=10000, diel=C, kappa=0.127315, cut=1000, gb=1, dielc=1.000000, temp0=298.150000', '_MMPBSA_complex_nm.mdcrd.0']
  File "/Users/jsmith/amber-install/bin/MMPBSA.py", line 100, in <module>
    app.run_mmpbsa()
  File "/Users/jsmith/amber-install/lib/python3.6/site-packages/MMPBSA_mods/main.py", line 218, in run_mmpbsa
    self.calc_list.run(rank, self.stdout)
  File "/Users/jsmith/amber-install/lib/python3.6/site-packages/MMPBSA_mods/calculation.py", line 82, in run
    calc.run(rank, stdout=stdout, stderr=stderr)
  File "/Users/jsmith/amber-install/lib/python3.6/site-packages/MMPBSA_mods/calculation.py", line 323, in run
    Calculation.run(self, rank, stdout=self.output % rank)
  File "/Users/jsmith/amber-install/lib/python3.6/site-packages/MMPBSA_mods/calculation.py", line 157, in run
    self.prmtop))
CalcError: /Users/jsmith/amber-install/bin/mmpbsa_py_nabnmode failed with prmtop complex.prmtop!
Exiting. All files have been retained.
```

It's segfaulting:
```
/Users/jsmith/amber-install/bin/mmpbsa_py_nabnmode _MMPBSA_complex.pdb complex.prmtop 50000 0.001 'ntpr=10000, diel=C, kappa=0.127315, cut=1000, gb=1, dielc=1.000000, temp0=298.150000' _MMPBSA_complex_nm.mdcrd.0
Segmentation fault: 11
```
Unfortunately I cannot debug it because I don't have permission to debug on SDSC `force`

**Comment by hainm** [comment]
In my case, got libreadline error

```
AmberTools/test/mmpbsa_py/07_Comprehensive $ cat mmpbsa.out 
Loading and checking parameter files for compatibility...
cpptraj found! Using /Users/haichit/amber_git/cmake/stable/bin/cpptraj
sander found! Using /Users/haichit/amber_git/cmake/stable/bin/sander
mmpbsa_py_nabnmode found! Using /Users/haichit/amber_git/cmake/stable/bin/mmpbsa_py_nabnmode
Preparing trajectories for simulation...
dyld: Library not loaded: libreadline.6.2.dylib
  Referenced from: /Users/haichit/amber_git/cmake/stable/bin/cpptraj
  Reason: image not found
```

**Comment by hainm** [comment]
```
$ otool -L `which cpptraj`
/Users/haichit/amber_git/cmake/stable/bin/cpptraj:
	@rpath/libbz2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	libreadline.6.2.dylib (compatibility version 6.0.0, current version 6.2.0)
	@rpath/libxdrfile.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libsander.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/fftw/lib/libfftw3.3.dylib (compatibility version 9.0.0, current version 9.5.0)
	@rpath/libemil.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libsff_fortran.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libarpack.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	@rpath/libamber_common.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libnetcdff.6.dylib (compatibility version 6.0.0, current version 6.1.1)
	@rpath/libnetcdf.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/local/gfortran/lib/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/gfortran/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/gfortran/lib/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/gfortran/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.22.0)
```

**Comment by multiplemonomials** [comment]
Which libreadline did Amber link to?  You can find out using `-DPRINT_PACKAGING_REPORT=TRUE`.

**Comment by hainm** [comment]
it's linked to `-- readline - /Users/haichit/miniconda3/lib/libreadline.dylib`
But I do see this log too 
`-- Installing: /Users/haichit/amber_git/cmake/stable/lib/libreadline.dylib`

**Comment by multiplemonomials** [comment]
Can you run `otool -D /Users/haichit/miniconda3/lib/libreadline.dylib`?

**Comment by multiplemonomials** [comment]
Also, I found out why `pymsmt` is dying:
```
******************************************************************
*               Welcome to use the MCPB.py program               *
*                          Version 3.0                           *
*                       Author: Pengfei Li                       *
*                      Merz Research Group                       *
*                   Michigan State University                    *
*                              AND                               *
*                 Hammes-Schiffer Research Group                 *
*           University of Illinois at Urbana-Champaign           *
******************************************************************
The input file you are using is : 1A5T.in
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
The following is the input variable you have:
The variable ion_ids is :  [5065]
The variable ion_info is :  []
The variable ion_mol2files is :  ['ZN.mol2']
The variable original_pdb is :  1A5T_fixed_H.pdb
The variable add_bonded_pairs is :  []
The variable add_redcrd is :  0
The variable additional_resids is :  []
The variable anglefc_avg is :  0
The variable bondfc_avg is :  0
The variable chgfix_resids is :  []
The variable cut_off is :  2.8
The variable force_field is :  ff14SB
The variable frcmod_files is :  []
The variable gaff is :  1
The variable group_name is :  1A5T
The variable ion_paraset is :  CM (Only for nonbonded model)
The variable large_opt is :  0
The variable lgmodel_chg is :  -99
The variable lgmodel_spin is :  -99
             -99 means program will assign a charge automatically.
The variable naa_mol2files is :  []
The variable scale_factor is :  1.0
             ATTENTION: This is the scale factor of frequency. The 
             force constants will be scaled by multiplying the square
             of scale_factor.
The variable smmodel_chg is :  -99
The variable smmodel_spin is :  -99
             -99 means program will assign a charge automatically.
The variable software_version is :  g03
The variable sqm_opt is :  0
The variable water_model is :  TIP3P
The variable xstru is :  0
******************************************************************
*                                                                *
*===================Generate the Initial frcmod file=============*
*                                                                *
******************************************************************
Traceback (most recent call last):
  File "/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/bin/MCPB.py", line 657, in <module>
    ff_choice, gaff, frcmodfs, watermodel)
  File "/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/lib64/python3.4/site-packages/pymsmt/mcpb/gene_pre_frcmod_file.py", line 54, in gene_pre_frcmod_file
    Params = get_parm_dict(ffchoice, gaff, frcmodfs)
  File "/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/lib64/python3.4/site-packages/pymsmt/lib.py", line 510, in get_parm_dict
    parmdict = read_dat_file(FF_DICT[ff_choice].datf)
  File "/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/lib64/python3.4/site-packages/pymsmt/lib.py", line 324, in read_dat_file
    for i in xrange(2, count+1):
NameError: name 'xrange' is not defined
```

This is not the first Python 3 compatibility issue I've seen in this program...

**Comment by multiplemonomials** [comment]
Should I email Pengfeng, or just stick a 
```python
from builtins import range
```
into that file?

**Comment by hainm** [comment]
> $ otool -D /Users/haichit/miniconda3/lib/libreadline.dylib
/Users/haichit/miniconda3/lib/libreadline.dylib:
libreadline.6.2.dylib

> NameError: name 'xrange' is not defined

i think it's fine to just change 'xrange' to 'range' (no need "from builtins import range").

**Comment by multiplemonomials** [comment]
OK, I think your Miniconda install is old or messed up.  That should not be the install_name, since it essentially disallows other programs from linking to the library.  Here's what I get with OS X Miniconda that I installed a week ago:
 
```
force:lib jsmith$ pwd
/Users/jsmith/miniconda3/lib
force:lib jsmith$ otool -D libreadline.dylib
libreadline.dylib:
@rpath/libreadline.7.dylib
```

This `install_name` is correct, and allows other apps to link with the library.  I know this is a pain, but can you try reinstalling or updating Miniconda to see if that corrects the broken `install_name`?

**Comment by hainm** [comment]
yeah, update miniconda (actually created new conda env) does solve the issue. thanks.

**Comment by multiplemonomials** [comment]
OK I tracked down the error with `MMPBSA.py` on the CI machine.
```
/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/bin/MMPBSA.py -O -i mmpbsa.in -sp complex_solvated.prmtop -cp complex.prmtop -rp receptor.prmtop -lp ligand.prmtop -y complex_solvated.mdcrd -yr receptor_solvated.mdcrd -yl ligand_solvated.mdcrd -srp receptor_solvated.prmtop -slp ligand_solvated.prmtop -o FINAL_RESULTS_MMPBSA_1.dat


Loading and checking parameter files for compatibility...
sander found! Using /iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/bin/sander
mmpbsa_py_nabnmode found! Using /iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/bin/mmpbsa_py_nabnmode
cpptraj found! Using /iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/bin/cpptraj
Preparing trajectories for simulation...
  File "/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/bin/MMPBSA.py", line 99, in <module>
    app.file_setup()
  File "/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/lib64/python3.4/site-packages/MMPBSA_mods/main.py", line 169, in file_setup
    self.normal_system, self.mutant_system, self.pre)
  File "/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/lib64/python3.4/site-packages/MMPBSA_mods/make_trajs.py", line 298, in make_mutant_trajectories
    from alamdcrd import MutantMdcrd, GlyMutantMdcrd
ImportError: No module named 'alamdcrd'
```

Any ideas @hainm?

**Comment by multiplemonomials** [comment]
```
ls /iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/lib64/python3.4/site-packages/MMPBSA_mods
alamdcrd.py
amber_outputs.py
API.py
calculation.py
commandlineparser.py
createinput.py
exceptions.py
fake_mpi.py
findprogs.py
infofile.py
__init__.py
input_parser.py
main.py
make_trajs.py
output_file.py
parm_setup.py
__pycache__
timer.py
utils.py
```

**Comment by hainm** [comment]
I am not sure. Can you try with python 2.7?

> MPBSA_mods/make_trajs.py", line 298, in make_mutant_trajectories
>  from alamdcrd import MutantMdcrd, GlyMutantMdcrd

this is old style python 2 syntax to implicitly import the module in the same package. 
In py3, I think should be

```
from MPBSA_mods.alamdcrd import ...
# or
from .alamdcrd import ...
```

If I remember correctly, mmpbsa_py use 2to3 to convert its code from py2 style to py3. @swails know better about this package.

**Comment by multiplemonomials** [comment]
@swails Do you have any idea about this problem?

**Comment by swails** [comment]
The last time I touched mmpbsa was years before I switched to py3, and it was the program I essentially learned python on. 

2to3 is currently being used to support py3, I think. So not using that is likely to cause problems.
