### ISSUE TITLE
Pysander doesn't use the right RPATH on OS X

### ISSUE THREAD

**Issue by multiplemonomials** [Amber-MD/cmake-buildscripts#70]
Error message:
```

Could not import the compiled Python-sander interface. Make sure you have the Python development libraries installed and that you have sourced amber.sh or amber.cshTraceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/travis/TMP/install/lib/python2.7/site-packages/sander/__init__.py", line 14, in <module>

    from . import pysander as _pys

ImportError: dlopen(/Users/travis/TMP/install/lib/python2.7/site-packages/sander/pysander.so, 2): Library not loaded: @rpath/libsander.dylib

  Referenced from: /Users/travis/TMP/install/lib/python2.7/site-packages/sander/pysander.so

  Reason: image not found
```

Pysander's build commands:
```

Scanning dependencies of target pysander

[100%] Building pysander native library

running build

running build_py

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/lib.macosx-10.7-x86_64-2.7

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/lib.macosx-10.7-x86_64-2.7/sander

copying sander/__init__.py -> /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/lib.macosx-10.7-x86_64-2.7/sander

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/lib.macosx-10.7-x86_64-2.7/sanderles

copying sanderles/__init__.py -> /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/lib.macosx-10.7-x86_64-2.7/sanderles

running build_ext

building 'sander.pysander' extension

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7/sander

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7/sander/src

clang -fno-strict-aliasing -I/Users/travis/miniconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/travis/amber16/AmberTools/src/include -I/Users/travis/amber16/AmberTools/src/sander -I/Users/travis/miniconda/include/python2.7 -c sander/src/pysandermodule.c -o /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7/sander/src/pysandermodule.o

clang -bundle -undefined dynamic_lookup -L/Users/travis/miniconda/lib -arch x86_64 -arch x86_64 /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7/sander/src/pysandermodule.o -L/Users/travis/TMP/build/AmberTools/src/sander -L/Users/travis/TMP/build/AmberTools/src/sander -L/Users/travis/miniconda/lib -lsander -o /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/lib.macosx-10.7-x86_64-2.7/sander/pysander.so

building 'sanderles.pysander' extension

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7/sanderles

creating /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7/sanderles/src

clang -fno-strict-aliasing -I/Users/travis/miniconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DLES -I/Users/travis/amber16/AmberTools/src/include -I/Users/travis/amber16/AmberTools/src/sander -I/Users/travis/miniconda/include/python2.7 -c sanderles/src/pysandermodule.c -o /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7/sanderles/src/pysandermodule.o

clang -bundle -undefined dynamic_lookup -L/Users/travis/miniconda/lib -arch x86_64 -arch x86_64 /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/temp.macosx-10.7-x86_64-2.7/sanderles/src/pysandermodule.o -L/Users/travis/TMP/build/AmberTools/src/sander -L/Users/travis/TMP/build/AmberTools/src/sander -L/Users/travis/miniconda/lib -lsanderles -o /Users/travis/TMP/build/AmberTools/src/pysander/CMakeFiles/pysander-build/lib.macosx-10.7-x86_64-2.7/sanderles/pysander.so

[100%] Built target pysander
```

**Comment by multiplemonomials** [comment]
@hainm I figured out how to fix this!  I feel like you said you were struggling to reproduce it, but I was able to get it to break just by running `unset DYLD_LIBRARY_PATH`.

The fix is to set the following environment variable during the Pysander build:
```
 LDFLAGS="-Wl,-rpath,@loader_path/../../..
```
and the following during the pytraj build:
```
LDFLAGS="-Wl,-rpath,@loader_path/../../../../.."
```

Do you think it would be good to add these to the `setup.py` scripts?  I can pass them from CMake but it seems a bit ugly.

**Comment by hainm** [comment]
I think it's fine to add that if pytraj is in amber + MacOS. Go ahead to make changes. thanks.
