### ISSUE TITLE
Some tests require config.h

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#85]
I just have a quick look at jenkins build from here: https://github.com/Amber-MD/cmake-buildscripts/issues/84#issuecomment-338844627

Those are several things you might know but I open here to keep track.

From: http://www.jasonswails.com:8888/job/Amber/job/AmberCI/88/consoleFull

- error: bad install directory or PYTHONPATH
- /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lThreads::Threads
collect2: error: ld returned 1 exit status (and most (all?) nab tests)

-
```
cd mmpbsa_py && make test
make[1]: Entering directory '/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/AmberCI/AmberTools/test/mmpbsa_py'
cd 07_Comprehensive && ./Run.comprehensive
./Run.comprehensive: Program error
make[1]: [Makefile:23: COMPREHENSIVE] Error 1 (ignored)
make[1]: Leaving directory '/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/AmberCI/AmberTools/test/mmpbsa_py'
cd parmed/normal_prmtop && ./Run.parmed
./Run.parmed: Program error
make: *** [Makefile:249: test.parmed] Error 1
```

- 
```
/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/AmberCI/AmberTools/test/../../AmberTools/src/pdb4amber/tests/files/amberlite && ./Run.pdb4amber
pdb4amber -i 3ptb.pdb -o 3ptb_amber_dpy.pdb -dpy
  ./Run.pdb4amber:  Program error
```

- 
```
cd cpinutil && ./Run.cpin
Traceback (most recent call last):
  File "/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/master/bin/cpinutil.py", line 12, in <module>
    from parmed.amber import AmberParm
ImportError: No module named 'parmed'
```

- 

```
cd pymsmt/mcpb/g03 && ./Run.pymsmt
./Run.pymsmt: Program error
make: *** [Makefile:107: test.pymsmt] Error 1
```

- 
```
cd sanderapi && make test
make[1]: Entering directory '/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/AmberCI/test/sanderapi'
Makefile:1: ../../config.h: No such file or directory
make[1]: *** No rule to make target '../../config.h'.
make[1]: Failed to remake makefile '../../config.h'.
make[2]: Entering directory '/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/AmberCI/test/sanderapi'
Makefile:1: ../../config.h: No such file or directory
make[2]: *** No rule to make target '../../config.h'.
make[2]: Failed to remake makefile '../../config.h'.
```

**Comment by hainm** [comment]
seems like you need to make a fake config.h for testing.
This is a short version I've been using
```
INSTALLTYPE=serial
AMBER_SOURCE=/Users/haichit/amber_git/amber
AMBER_PREFIX=/Users/haichit/amber_git/cmake/tmp
BINDIR=/Users/haichit/amber_git/cmake/tmp/bin
DATDIR=/Users/haichit/amber_git/cmake/tmp/dat
LIBDIR=/Users/haichit/amber_git/cmake/tmp/lib
INCDIR=/Users/haichit/amber_git/cmake/tmp/include
PYTHON=python
SKIP_PYTHON=no
SHARED_SUFFIX=.dylib
```

**Comment by multiplemonomials** [comment]
The Python errors are due to the test system having `lib64/site-packages` PYTHONPATHs, which the build system doesn't support yet.  This is Issue #61.

**Comment by multiplemonomials** [comment]
With the commit I just pushed, the build system will now generate its own `config.h`, which should fix many of the tests.

**Comment by hainm** [comment]
I've check the log. What happens with "/home/jamie/anaconda3/lib"?

```
commit 1f6980a468d27fd035fa9c15e55b85e633ea86e3
Author: Jamie Smith <jsmith@crackofdawn.onmicrosoft.com>
Date:   Thu Nov 9 20:55:28 2017 -0800

    CMake: generate a config.h containing a subset of the Makefile build system's config.h variables.  This should get the tests a lot closer to working properly.

diff --git a/CMakeLists.txt b/CMakeLists.txt
index ba9d8e1..1c78dc2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -134,6 +134,9 @@ else() #include all configuration segments
                list(APPEND REQUIRED_3RDPARTY_TOOLS fftw)
        endif()
        
+ list(APPEND CMAKE_LIBRARY_PATH "/home/jamie/anaconda3/lib")
+ list(APPEND CMAKE_LIBRARY_PATH "/home/jamie/anaconda3/include")
+     
```

**Comment by multiplemonomials** [comment]
Oh, whoops!  That was part of the code that I was testing to fix the Anaconda issue, and apparently I forgot to take it out.  I'll get rid of it.

**Comment by multiplemonomials** [comment]
@hainm 
Any idea what's going on here (from the Jenkins AmberCI build):
```
make[1]: Entering directory '/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/AmberCI/AmberTools/test/pytraj'
Testing pytraj MPI
 /usr/bin/python test_mpi.py
Traceback (most recent call last):
  File "test_mpi.py", line 14, in <module>
    aa_eq(pt.tools.dict_to_ndarray(parallel_data), serial_data)
  File "/usr/lib64/python3.4/site-packages/numpy/testing/utils.py", line 497, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/lib64/python3.4/site-packages/numpy/testing/utils.py", line 892, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python3.4/site-packages/numpy/testing/utils.py", line 668, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 4 decimals

(shapes (1, 10), (10,) mismatch)
 x: array([[  4.4429e-01,   3.3826e-01,   3.8589e-01,   3.6606e-01,
          2.7759e-01,   3.3548e-01,   1.7358e-01,   5.9605e-08,
          2.5413e-01,   3.9402e-01]])
 y: array([  4.4429e-01,   3.3826e-01,   3.8589e-01,   3.6606e-01,
         2.7759e-01,   3.3548e-01,   1.7358e-01,   5.9605e-08,
         2.5413e-01,   3.9402e-01])
test.pytraj:  Program error
```

**Comment by multiplemonomials** [comment]
They really do look equal.

**Comment by hainm** [comment]
because the shape of array different. I guess I miss this since I never compile AmberTools MPI :D. Will update it.

**Comment by hainm** [comment]
should be fixed now

```
$ mpirun -n 3 python test_mpi.py 
PASSED
```

**Comment by hainm** [comment]
oh boy, you changed the mpi test

```
commit 0cfd21a510b259243316ce68f075b6ab40ecf2ea
Author: Jamie Smith <jsmith@crackofdawn.onmicrosoft.com>
Date:   Sat Jul 29 12:20:32 2017 -0700

    Fix merge conflicts in tests from when I merged my changes with the AMBER_PREFIX changes

diff --git a/AmberTools/test/pytraj/Makefile b/AmberTools/test/pytraj/Makefile
index 9d60eea..afc4003 100644
--- a/AmberTools/test/pytraj/Makefile
+++ b/AmberTools/test/pytraj/Makefile
@@ -1,16 +1,5 @@
 
 test.pytraj:
-<<<<<<< HEAD
-ifeq ($(INSTALLTYPE), serial)
-   @echo "Testing pytraj"
-   @echo "python test.py"
-   @python test.py || echo "$@:  Program error"
-else ifeq ($(INSTALLTYPE), parallel)
-   @echo "Testing pytraj MPI"
-   @echo "$(DO_PARALLEL) python test_mpi.py"
-   $(DO_PARALLEL) python test_mpi.py || echo "$@:  Program error"
-endif
-=======
```

**Comment by hainm** [comment]
```
-else ifeq ($(INSTALLTYPE), parallel)
-   @echo "Testing pytraj MPI"
-   @echo "$(DO_PARALLEL) python test_mpi.py"
-   $(DO_PARALLEL) python test_mpi.py || echo "$@:  Program error"
-endif
```

I think we need to add this back

**Comment by hainm** [comment]
> oh boy, you changed the mpi test

oops, never mind about my comments. I do see the parallel testing. Sorry for the false alarm.

```
        elif [ "$(INSTALLTYPE)" = 'parallel' ] ; then \
        echo "Testing pytraj MPI" ;\
        echo "$(DO_PARALLEL) $(PYTHON) test_mpi.py" ;\
        $(DO_PARALLEL) $(PYTHON) test_mpi.py || echo "$@:  Program error" ;\
        else \
        echo "Error: Undefined value for config.h variable INSTALLTYPE." ;\
        exit 2 ;\
        fi ;\
```

**Comment by multiplemonomials** [comment]
OK I think this is fixed for now.  I still have #18 open for test error in general,
